# Generated by Django 6.0.5 on 2026-05-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
